Add controllers
DanielSJavaDev/java-shareit pull request #2
Opened 2022-12-26 22:35 UTC by DanielSJavaDev

2022-12-27 18:46 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо сделано, но можно улучшить:

1) Давай поправим что отметил
2) private почему то используется скромно
3) @JsonFormat не заметил
4) Можно поизучать валидацию при помощи аннотаций из spring validation

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  public class Booking {
private к полям лучше бы добавить

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@RequiredArgsConstructor
Я же правильно понимаю что это сделано задел на будущее?

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
private к полям лучше бы добавить

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getAllByUserId(@Valid @RequestHeader(value = "X-Sharer-User-Id") int id) {
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        validator.userValidator(id);
Лучше заниматься валидацией в контроллере

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (item.getName() == null && item.getDescription() == null && item.getAvailable() != null) {
Нельзя придумать как ниже проверки оптимальнее записать,? А то выглядит тяжко и громоздко

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NoSuchElementException("can't find item");
Добавить критерий по которому не был найден элемент

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +public class ItemValidator {
В валидаторе использовать сервисы это на мой вгляд "плохой тон", но не критично

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
private поля может сделаем?

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  public class ItemRequest {
private поля может сделаем?

2022-12-27 18:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/MailValidator.java
> +    private final HashMap<Integer, String> emailValidator;
хранить список емейлов в валидаторе звучит и выглядит кхм небезопасно

2023-01-05 13:12 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@RequiredArgsConstructor
Всё верно, решил сразу накидать минимальную структуру для моделек и контроллеров

2023-01-05 13:23 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (item.getName() == null && item.getDescription() == null && item.getAvailable() != null) {
Это меня уже плавило после работы :D На свежую голову в 3 ифа эту задачу решил))

2023-01-05 13:26 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +public class ItemValidator {
Согласен, но пока у нас репозиторий внутри приложения, пришлось так сделать. Как бд подключим, эту часть уберу.

2023-01-05 19:34 UTC, krylov-sergey-sergeevich approved these changes
Привет, с Новым годом:)

Вижу правки - зачет!

2023-01-05 19:37 UTC, merged