feat: add bookings first iteration
DanielSJavaDev/java-shareit pull request #3
Opened 2023-01-13 22:15 UTC by DanielSJavaDev

2023-01-15 08:03 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, давай поправим по правкам и улучшим по следующим пунктам:
- Для чего файл .DS_Store ? Может его в gitignore закинуть и выкинуть из pr?
- Часто в логах есть такая штука как "что-то сделано" или "что-то не удалось сделать", но не указывается с каким объектом, это плохо тк затруднит в будущем понимание логов, всегда надо добавлять по возможности id того что/с чем взаимодействуем.

Поизучать в свободное время (и если получится применить тут, но это не обязательно к выполнению):
- @JsonFormat
- FOREIGN KEYS

Буду ждать с доработками =)

2023-01-15 08:03 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private void checkBookingsForComment(Long itemId, Long userId) {
Отлично что это не забыл

2023-01-15 21:55 UTC, DanielSJavaDev commented on src/main/resources/schema.sql
> +                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Не задавался этим вопросом, но мне казалось логичным поле с идентификатором генерить как identity))
Почитал статью https://www.red-gate.com/simple-talk/databases/sql-server/learn/sql-server-identity-column/ противоречий своей логике не обнаружил)))

2023-01-15 22:29 UTC, DanielSJavaDev commented
Привет! Что-то не нашёл у себя файл .DS_Store в проекте.
Информативности в логи добавил, JsonFormat к полям с датами добавил

2023-01-16 15:46 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-01-16 15:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +@SpringBootApplication(scanBasePackages = "ru.practicum.shareit")
А почему добавился пакет скан? Без него не работает?

2023-01-16 15:46 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd@HH:mm:ss.SSSZ")
"yyyy-MM-dd@HH:mm:ss.SSSZ" - давай данный паттерн вынесем в класс констант

2023-01-16 15:47 UTC, krylov-sergey-sergeevich commented
По этим комментариям просьба к следующему дз поправить

2023-01-16 19:34 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +@SpringBootApplication(scanBasePackages = "ru.practicum.shareit")
В прошлом спринте не запускалось приложение, пробовал разные варианты, забыл убрать

2023-01-16 19:36 UTC, merged