Add item requests
DanielSJavaDev/java-shareit pull request #4
Opened 2023-01-19 14:24 UTC by DanielSJavaDev

2023-01-21 19:40 UTC, krylov-sergey-sergeevich requested changes
Привет :) В целом неплохой pr, но кое что улучшим

1. Вижу что используешь verify в Mockito , но как то скромно если что достаточно полезная штука чтобы проверять что нет двойных вызовов где-то например

2) Доработать исключения чтобы было не так (это всех аналогичных исключений касается):
```java
throw new UserNotFoundException("unknown user with id " + userId)
```
а вот так: 
```java
throw new UserNotFoundException(userId)
```
Но при этом то что увидит человек при получение такого исключения не изменилось бы.

3) Прошу создать отдельный класс DateUtils и там сделать статичный метод now() и использовать его во всем приложение.

Причина: рано или поздно придется в реальной жизни обработку каких то кейсов с датой и лучше сразу уметь разрабатывать так что это вынесено и потом не нужно делать с болью

Буду ждать с правками =)

2023-01-21 19:40 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/PaginationConverter.java
> +public class PaginationConverter {
Хорошая утилита, правда вопрос точно ли ей надо быть компонентом

2023-01-21 19:40 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Jacksonized
Для чего это?

2023-01-24 13:13 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/PaginationConverter.java
> +public class PaginationConverter {
Не уверен, но в моём случае без этого никак))
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of constructor in ru.practicum.shareit.booking.BookingServiceImpl required a bean of type 'ru.practicum.shareit.PaginationConverter' that could not be found.

2023-01-24 13:15 UTC, DanielSJavaDev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Jacksonized
Для тестов, без этой аннотации возникает ошибка:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class ru.practicum.shareit.user.dto.UserDto]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `ru.practicum.shareit.user.dto.UserDto` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]

2023-01-24 13:46 UTC, DanielSJavaDev commented
Привет! 
1. По поводу тестов: я покрыл 99% кода тестами, но так и не прошёл проверку, помогло только удаление зависимости из пома и ребилд. Я на это убил 3+ полных дня и не хочу к тестам сейчас возвращаться. В будущем буду больше юзать verify.

2. Не очень понял, что нужно от ексепшенов? Добавить текст в параметры, чтобы при выбросе передавать только айдишник? Это было бы хорошо, но у меня в разных частях программы при выбросе одного и того же исключения разные тексты ошибки, например: "can't find user with id " + id, "incorrect user with id " + userId, "unknown user with id " + userId, "non-existent user with id " + userId и т.д. Они меняются в зависимости от контекста и мне так удобней их идентифицировать.
А по поводу "Но при этом то что увидит человек при получение такого исключения не изменилось бы." - все ексепшены видны только мне на сервере, по тз только один(UnsopportedStatus) должен возвращаться юзеру.

3. DateUtils.now() добавил в мапперы.

2023-01-24 15:23 UTC, krylov-sergey-sergeevich approved these changes
Привет, для зачета впринципе все ок. Отвечу ниже на сообщение:

1) Искренне сочувствую за 3 дня убитых на тесты, в этом все айти вбухивается много часов иногда на странные простые вещи
2) Если у тебя разный текст в исключениях то у тебя должны быть разные классы исключений, в больших проектах обычно сотни кастомных исключений. На счет "ексепшены видны только мне на сервере" в этом и суть чтобы ты потом в логах когда уронишь продакшен на десятки тысяч людей увидел подробный текст =)
3) Вопросов нет 

Удачи с следующим дз и на счет исключений рекомендую все же доработать =)

2023-01-24 15:56 UTC, DanielSJavaDev commented
Это не странные простые вещи, это забаганая проверка покрытия))
До дедлайна ещё много времени, постараюсь на 16фп проработать тему с исключениями.
Спасибо за ревью!)

2023-01-24 15:56 UTC, merged